// GENERATED FILE — do not edit by hand.
// Written by `navigator compile` from canonical content in content/concepts/.
//
// A concept appears once as a canonical `doc` entry under its primary
// category and as a `ref` entry under every other category it belongs to,
// so one page can be reached through several categories without becoming
// several pages. Tier 3 concepts are omitted from reader navigation.
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  conceptsSidebar: [
    {
      type: 'category',
      label: "Artificial Intelligence",
      collapsed: false,
      items: [
        {
          type: 'category',
          label: "Classical Machine Learning",
          collapsed: true,
          items: [
            { type: 'doc', id: "bayesian-networks", label: "Bayesian Networks" },
            { type: 'doc', id: "bias-variance", label: "Bias-Variance" },
            { type: 'doc', id: "conditional-random-fields", label: "Conditional Random Fields" },
            { type: 'doc', id: "dbscan", label: "DBSCAN" },
            { type: 'doc', id: "decision-trees", label: "Decision Trees" },
            { type: 'doc', id: "gaussian-processes", label: "Gaussian Processes" },
            { type: 'doc', id: "generalization", label: "Generalization" },
            { type: 'doc', id: "generalized-linear-models", label: "Generalized Linear Models" },
            { type: 'doc', id: "gradient-boosting", label: "Gradient Boosting" },
            { type: 'doc', id: "hidden-markov-models", label: "Hidden Markov Models" },
            { type: 'doc', id: "hierarchical-clustering", label: "Hierarchical Clustering" },
            { type: 'doc', id: "independent-component-analysis", label: "Independent Component Analysis" },
            { type: 'doc', id: "kernel-methods", label: "Kernel Methods" },
            { type: 'doc', id: "linear-regression", label: "Linear Regression" },
            { type: 'doc', id: "logistic-regression", label: "Logistic Regression" },
            { type: 'doc', id: "naive-bayes", label: "Naive Bayes" },
            { type: 'doc', id: "pac-learning", label: "PAC Learning" },
            { type: 'doc', id: "principal-component-analysis", label: "Principal Component Analysis" },
            { type: 'doc', id: "random-forests", label: "Random Forests" },
            { type: 'doc', id: "spectral-clustering", label: "Spectral Clustering" },
            { type: 'doc', id: "support-vector-machines", label: "Support Vector Machines" },
            { type: 'doc', id: "umap", label: "UMAP" },
            { type: 'doc', id: "vc-dimension", label: "VC Dimension" },
            { type: 'doc', id: "k-means", label: "k-Means" },
            { type: 'doc', id: "k-nearest-neighbors", label: "k-Nearest Neighbors" },
            { type: 'doc', id: "t-sne", label: "t-SNE" },
          ],
        },
        {
          type: 'category',
          label: "Computer Vision",
          collapsed: true,
          items: [
            { type: 'ref', id: "lenet", label: "LeNet" },
            { type: 'ref', id: "receptive-field", label: "Receptive Field" },
            { type: 'doc', id: "resnet", label: "ResNet" },
            { type: 'doc', id: "vgg", label: "VGG" },
          ],
        },
        {
          type: 'category',
          label: "Deep Learning — Architectures",
          collapsed: true,
          items: [
            { type: 'doc', id: "attention", label: "Attention" },
            { type: 'doc', id: "autoencoders", label: "Autoencoders" },
            { type: 'doc', id: "boltzmann-machines", label: "Boltzmann Machines" },
            { type: 'doc', id: "capsule-networks", label: "Capsule Networks" },
            { type: 'doc', id: "clifford-neural-networks", label: "Clifford Neural Networks" },
            { type: 'doc', id: "convnext", label: "ConvNeXt" },
            { type: 'doc', id: "convolutional-layer", label: "Convolutional Layer" },
            { type: 'doc', id: "convolutional-networks", label: "Convolutional Networks" },
            { type: 'doc', id: "diffusion-models", label: "Diffusion Models" },
            { type: 'doc', id: "energy-based-models", label: "Energy-Based Models" },
            { type: 'doc', id: "equivariance", label: "Equivariance" },
            { type: 'doc', id: "flow-matching", label: "Flow Matching" },
            { type: 'doc', id: "gru", label: "GRU" },
            { type: 'doc', id: "generative-adversarial-networks", label: "Generative Adversarial Networks" },
            { type: 'doc', id: "geometric-deep-learning", label: "Geometric Deep Learning" },
            { type: 'doc', id: "graph-attention-networks", label: "Graph Attention Networks" },
            { type: 'doc', id: "graph-convolutional-networks", label: "Graph Convolutional Networks" },
            { type: 'doc', id: "graph-neural-networks", label: "Graph Neural Networks" },
            { type: 'doc', id: "hopfield-networks", label: "Hopfield Networks" },
            { type: 'doc', id: "kolmogorov-arnold-networks", label: "Kolmogorov-Arnold Networks" },
            { type: 'doc', id: "lstm", label: "LSTM" },
            { type: 'doc', id: "lenet", label: "LeNet" },
            { type: 'doc', id: "mamba", label: "Mamba" },
            { type: 'doc', id: "message-passing", label: "Message Passing" },
            { type: 'doc', id: "mixture-of-experts", label: "Mixture of Experts" },
            { type: 'doc', id: "multilayer-perceptrons", label: "Multilayer Perceptrons" },
            { type: 'doc', id: "neural-odes", label: "Neural ODEs" },
            { type: 'doc', id: "neuromorphic-computing", label: "Neuromorphic Computing" },
            { type: 'doc', id: "normalizing-flows", label: "Normalizing Flows" },
            { type: 'doc', id: "perceptron", label: "Perceptron" },
            { type: 'doc', id: "pooling", label: "Pooling" },
            { type: 'doc', id: "positional-encoding", label: "Positional Encoding" },
            { type: 'doc', id: "quaternion-neural-networks", label: "Quaternion Neural Networks" },
            { type: 'doc', id: "rwkv", label: "RWKV" },
            { type: 'doc', id: "radial-basis-function-networks", label: "Radial Basis Function Networks" },
            { type: 'doc', id: "receptive-field", label: "Receptive Field" },
            { type: 'doc', id: "recurrent-neural-networks", label: "Recurrent Neural Networks" },
            { type: 'ref', id: "resnet", label: "ResNet" },
            { type: 'doc', id: "residual-connection", label: "Residual Connection" },
            { type: 'doc', id: "s4", label: "S4" },
            { type: 'doc', id: "self-organizing-maps", label: "Self-Organizing Maps" },
            { type: 'doc', id: "spherical-cnns", label: "Spherical CNNs" },
            { type: 'doc', id: "spiking-neural-networks", label: "Spiking Neural Networks" },
            { type: 'doc', id: "state-space-models", label: "State Space Models" },
            { type: 'doc', id: "transformers", label: "Transformers" },
            { type: 'ref', id: "translation-equivariance", label: "Translation Equivariance" },
            { type: 'ref', id: "vgg", label: "VGG" },
            { type: 'doc', id: "variational-autoencoders", label: "Variational Autoencoders" },
            { type: 'doc', id: "vision-transformer", label: "Vision Transformer" },
            { type: 'doc', id: "xlstm", label: "xLSTM" },
          ],
        },
        {
          type: 'category',
          label: "Deep Learning — Training",
          collapsed: true,
          items: [
            { type: 'doc', id: "adam", label: "Adam" },
            { type: 'doc', id: "backpropagation", label: "Backpropagation" },
            { type: 'doc', id: "backpropagation-through-convolution", label: "Backpropagation Through Convolution" },
            { type: 'doc', id: "batch-normalization", label: "Batch Normalization" },
            { type: 'doc', id: "distillation", label: "Distillation" },
            { type: 'doc', id: "initialization", label: "Initialization" },
            { type: 'doc', id: "layer-normalization", label: "Layer Normalization" },
            { type: 'doc', id: "learning-rate-schedules", label: "Learning-Rate Schedules" },
            { type: 'doc', id: "loss-functions", label: "Loss Functions" },
            { type: 'doc', id: "pruning", label: "Pruning" },
            { type: 'doc', id: "quantization", label: "Quantization" },
            { type: 'doc', id: "regularization", label: "Regularization" },
            { type: 'doc', id: "stochastic-gradient-descent", label: "Stochastic Gradient Descent" },
          ],
        },
        {
          type: 'category',
          label: "Learning Paradigms",
          collapsed: true,
          items: [
            { type: 'doc', id: "continual-learning", label: "Continual Learning" },
            { type: 'doc', id: "contrastive-learning", label: "Contrastive Learning" },
            { type: 'doc', id: "curriculum-learning", label: "Curriculum Learning" },
            { type: 'doc', id: "federated-learning", label: "Federated Learning" },
            { type: 'doc', id: "meta-learning", label: "Meta-Learning" },
            { type: 'doc', id: "self-supervised-learning", label: "Self-Supervised Learning" },
            { type: 'doc', id: "supervised-learning", label: "Supervised Learning" },
            { type: 'doc', id: "transfer-learning", label: "Transfer Learning" },
            { type: 'doc', id: "unsupervised-learning", label: "Unsupervised Learning" },
          ],
        },
        {
          type: 'category',
          label: "Reinforcement Learning",
          collapsed: true,
          items: [
            { type: 'doc', id: "actor-critic", label: "Actor-Critic" },
            { type: 'doc', id: "dqn", label: "DQN" },
            { type: 'doc', id: "dynamic-programming", label: "Dynamic Programming" },
            { type: 'doc', id: "imitation-learning", label: "Imitation Learning" },
            { type: 'doc', id: "inverse-reinforcement-learning", label: "Inverse Reinforcement Learning" },
            { type: 'doc', id: "markov-decision-processes", label: "Markov Decision Processes" },
            { type: 'doc', id: "model-based-reinforcement-learning", label: "Model-Based Reinforcement Learning" },
            { type: 'doc', id: "monte-carlo-methods", label: "Monte Carlo Methods" },
            { type: 'doc', id: "multi-agent-reinforcement-learning", label: "Multi-Agent Reinforcement Learning" },
            { type: 'doc', id: "multi-armed-bandits", label: "Multi-Armed Bandits" },
            { type: 'doc', id: "offline-reinforcement-learning", label: "Offline Reinforcement Learning" },
            { type: 'doc', id: "ppo", label: "PPO" },
            { type: 'doc', id: "policy-gradients", label: "Policy Gradients" },
            { type: 'doc', id: "q-learning", label: "Q-Learning" },
            { type: 'doc', id: "reinforce", label: "REINFORCE" },
            { type: 'doc', id: "rlaif", label: "RLAIF" },
            { type: 'doc', id: "rlhf", label: "RLHF" },
            { type: 'doc', id: "sac", label: "SAC" },
            { type: 'doc', id: "temporal-difference-learning", label: "Temporal-Difference Learning" },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: "Mathematics",
      collapsed: false,
      items: [
        {
          type: 'category',
          label: "Algebra",
          collapsed: true,
          items: [
            { type: 'doc', id: "clifford-algebra", label: "Clifford Algebra" },
            { type: 'doc', id: "complex-numbers", label: "Complex Numbers" },
            { type: 'doc', id: "field-theory", label: "Field Theory" },
            { type: 'doc', id: "galois-theory", label: "Galois Theory" },
            { type: 'doc', id: "geometric-algebra", label: "Geometric Algebra" },
            { type: 'doc', id: "group-theory", label: "Group Theory" },
            { type: 'doc', id: "homological-algebra", label: "Homological Algebra" },
            { type: 'doc', id: "lattice-theory", label: "Lattice Theory" },
            { type: 'doc', id: "lie-algebras", label: "Lie Algebras" },
            { type: 'doc', id: "octonions", label: "Octonions" },
            { type: 'doc', id: "order-theory", label: "Order Theory" },
            { type: 'doc', id: "quaternions", label: "Quaternions" },
            { type: 'doc', id: "representation-theory", label: "Representation Theory" },
            { type: 'doc', id: "ring-theory", label: "Ring Theory" },
          ],
        },
        {
          type: 'category',
          label: "Analysis",
          collapsed: true,
          items: [
            { type: 'doc', id: "banach-spaces", label: "Banach Spaces" },
            { type: 'doc', id: "calculus-of-variations", label: "Calculus of Variations" },
            { type: 'doc', id: "chaos", label: "Chaos" },
            { type: 'doc', id: "complex-analysis", label: "Complex Analysis" },
            { type: 'doc', id: "convolution", label: "Convolution" },
            { type: 'doc', id: "cross-correlation", label: "Cross-Correlation" },
            { type: 'doc', id: "dynamical-systems", label: "Dynamical Systems" },
            { type: 'doc', id: "fourier-analysis", label: "Fourier Analysis" },
            { type: 'doc', id: "functional-analysis", label: "Functional Analysis" },
            { type: 'doc', id: "harmonic-analysis", label: "Harmonic Analysis" },
            { type: 'doc', id: "hilbert-spaces", label: "Hilbert Spaces" },
            { type: 'doc', id: "measure-theory", label: "Measure Theory" },
            { type: 'doc', id: "multivariable-calculus", label: "Multivariable Calculus" },
            { type: 'doc', id: "operators", label: "Operators" },
            { type: 'doc', id: "ordinary-differential-equations", label: "Ordinary Differential Equations" },
            { type: 'doc', id: "partial-differential-equations", label: "Partial Differential Equations" },
            { type: 'doc', id: "real-analysis", label: "Real Analysis" },
            { type: 'doc', id: "single-variable-calculus", label: "Single-Variable Calculus" },
            { type: 'doc', id: "translation-equivariance", label: "Translation Equivariance" },
            { type: 'doc', id: "vector-calculus", label: "Vector Calculus" },
            { type: 'doc', id: "wavelets", label: "Wavelets" },
          ],
        },
        {
          type: 'category',
          label: "Foundations",
          collapsed: true,
          items: [
            {
              type: 'category',
              label: "Formal Verification",
              collapsed: true,
              items: [
                { type: 'doc', id: "coq", label: "Coq" },
                { type: 'doc', id: "lean", label: "Lean" },
              ],
            },
            {
              type: 'category',
              label: "Logic & Proof",
              collapsed: true,
              items: [
                { type: 'doc', id: "first-order-logic", label: "First-Order Logic" },
                { type: 'doc', id: "proof-theory", label: "Proof Theory" },
                { type: 'doc', id: "propositional-logic", label: "Propositional Logic" },
              ],
            },
            { type: 'doc', id: "category-theory", label: "Category Theory" },
            { type: 'doc', id: "computability-theory", label: "Computability Theory" },
            { type: 'doc', id: "model-theory", label: "Model Theory" },
            { type: 'doc', id: "set-theory", label: "Set Theory" },
          ],
        },
        {
          type: 'category',
          label: "Geometry & Topology",
          collapsed: true,
          items: [
            { type: 'doc', id: "algebraic-geometry", label: "Algebraic Geometry" },
            { type: 'doc', id: "algebraic-topology", label: "Algebraic Topology" },
            { type: 'doc', id: "convex-geometry", label: "Convex Geometry" },
            { type: 'doc', id: "curvature", label: "Curvature" },
            { type: 'doc', id: "differential-geometry", label: "Differential Geometry" },
            { type: 'doc', id: "differential-topology", label: "Differential Topology" },
            { type: 'doc', id: "euclidean-geometry", label: "Euclidean Geometry" },
            { type: 'doc', id: "fractal-geometry", label: "Fractal Geometry" },
            { type: 'doc', id: "hyperbolic-geometry", label: "Hyperbolic Geometry" },
            { type: 'doc', id: "lie-groups", label: "Lie Groups" },
            { type: 'doc', id: "manifolds", label: "Manifolds" },
            { type: 'doc', id: "non-euclidean-geometry", label: "Non-Euclidean Geometry" },
            { type: 'doc', id: "point-set-topology", label: "Point-Set Topology" },
            { type: 'doc', id: "renormalization", label: "Renormalization" },
            { type: 'doc', id: "spherical-geometry", label: "Spherical Geometry" },
          ],
        },
        {
          type: 'category',
          label: "Linear & Multilinear Algebra",
          collapsed: true,
          items: [
            { type: 'doc', id: "matrix-decompositions", label: "Matrix Decompositions" },
            { type: 'doc', id: "matrix-theory", label: "Matrix Theory" },
            { type: 'doc', id: "spectral-theory", label: "Spectral Theory" },
            { type: 'doc', id: "tensor-decomposition", label: "Tensor Decomposition" },
            { type: 'doc', id: "tensors", label: "Tensors" },
            { type: 'doc', id: "vector-spaces", label: "Vector Spaces" },
          ],
        },
        {
          type: 'category',
          label: "Mathematical Physics",
          collapsed: true,
          items: [
            { type: 'doc', id: "hamiltonian-mechanics", label: "Hamiltonian Mechanics" },
            { type: 'doc', id: "statistical-mechanics", label: "Statistical Mechanics" },
          ],
        },
        {
          type: 'category',
          label: "Number Theory",
          collapsed: true,
          items: [
            { type: 'doc', id: "algebraic-number-theory", label: "Algebraic Number Theory" },
            { type: 'doc', id: "analytic-number-theory", label: "Analytic Number Theory" },
            { type: 'doc', id: "elementary-number-theory", label: "Elementary Number Theory" },
          ],
        },
        {
          type: 'category',
          label: "Optimization",
          collapsed: true,
          items: [
            { type: 'doc', id: "combinatorial-optimization", label: "Combinatorial Optimization" },
            { type: 'doc', id: "convex-optimization", label: "Convex Optimization" },
            { type: 'doc', id: "integer-programming", label: "Integer Programming" },
            { type: 'doc', id: "nonconvex-optimization", label: "Nonconvex Optimization" },
            { type: 'doc', id: "optimal-transport", label: "Optimal Transport" },
            { type: 'doc', id: "stochastic-optimization", label: "Stochastic Optimization" },
            { type: 'doc', id: "variational-methods", label: "Variational Methods" },
          ],
        },
        {
          type: 'category',
          label: "Probability & Statistics",
          collapsed: true,
          items: [
            { type: 'doc', id: "bayesian-inference", label: "Bayesian Inference" },
            { type: 'doc', id: "concentration-inequalities", label: "Concentration Inequalities" },
            { type: 'doc', id: "frequentist-inference", label: "Frequentist Inference" },
            { type: 'doc', id: "high-dimensional-statistics", label: "High-Dimensional Statistics" },
            { type: 'doc', id: "martingales", label: "Martingales" },
            { type: 'doc', id: "probability-theory", label: "Probability Theory" },
            { type: 'doc', id: "probability-and-computing", label: "Probability and Computing" },
            { type: 'doc', id: "random-matrix-theory", label: "Random Matrix Theory" },
            { type: 'doc', id: "stochastic-processes", label: "Stochastic Processes" },
          ],
        },
        {
          type: 'category',
          label: "Theory of Computation",
          collapsed: true,
          items: [
            { type: 'doc', id: "automata", label: "Automata" },
            { type: 'doc', id: "computational-complexity", label: "Computational Complexity" },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: "Programming",
      collapsed: false,
      items: [
        {
          type: 'category',
          label: "Data Structures & Algorithms",
          collapsed: true,
          items: [
            { type: 'doc', id: "complexity-analysis", label: "Complexity Analysis" },
            { type: 'doc', id: "core-data-structures", label: "Core Data Structures" },
            { type: 'doc', id: "graph-algorithms", label: "Graph Algorithms" },
            { type: 'doc', id: "searching", label: "Searching" },
            { type: 'doc', id: "sorting", label: "Sorting" },
          ],
        },
        {
          type: 'category',
          label: "Languages",
          collapsed: true,
          items: [
            {
              type: 'category',
              label: "Paradigms",
              collapsed: true,
              items: [
                { type: 'doc', id: "array-programming", label: "Array Programming" },
                { type: 'doc', id: "functional-programming", label: "Functional Programming" },
                { type: 'doc', id: "imperative-programming", label: "Imperative Programming" },
                { type: 'doc', id: "object-oriented-programming", label: "Object-Oriented Programming" },
              ],
            },
            { type: 'doc', id: "assembly", label: "Assembly" },
            { type: 'doc', id: "c-language", label: "C" },
            { type: 'doc', id: "cpp", label: "C++" },
            { type: 'doc', id: "cuda", label: "CUDA" },
            { type: 'doc', id: "gpu-kernels", label: "GPU Kernels" },
            { type: 'doc', id: "go", label: "Go" },
            { type: 'doc', id: "haskell", label: "Haskell" },
            { type: 'doc', id: "javascript", label: "JavaScript" },
            { type: 'doc', id: "julia", label: "Julia" },
            { type: 'doc', id: "lisp", label: "Lisp" },
            { type: 'doc', id: "matlab", label: "MATLAB" },
            { type: 'doc', id: "python", label: "Python" },
            { type: 'doc', id: "r-language", label: "R" },
            { type: 'doc', id: "rust", label: "Rust" },
            { type: 'doc', id: "typescript", label: "TypeScript" },
          ],
        },
        {
          type: 'category',
          label: "ML Engineering",
          collapsed: true,
          items: [
            { type: 'doc', id: "deployment", label: "Deployment" },
            { type: 'doc', id: "edge-inference", label: "Edge Inference" },
            { type: 'doc', id: "experiment-tracking", label: "Experiment Tracking" },
            { type: 'doc', id: "jax", label: "JAX" },
            { type: 'doc', id: "ollama", label: "Ollama" },
            { type: 'doc', id: "pytorch", label: "PyTorch" },
            { type: 'doc', id: "training-infrastructure", label: "Training Infrastructure" },
          ],
        },
        {
          type: 'category',
          label: "Software Practice",
          collapsed: true,
          items: [
            { type: 'doc', id: "apis", label: "APIs" },
            { type: 'doc', id: "containers", label: "Containers" },
            { type: 'doc', id: "continuous-delivery", label: "Continuous Delivery" },
            { type: 'doc', id: "continuous-integration", label: "Continuous Integration" },
            { type: 'doc', id: "design-patterns", label: "Design Patterns" },
            { type: 'doc', id: "model-context-protocol", label: "Model Context Protocol" },
            { type: 'doc', id: "protocols", label: "Protocols" },
            { type: 'doc', id: "testing", label: "Testing" },
            { type: 'doc', id: "version-control", label: "Version Control" },
          ],
        },
        {
          type: 'category',
          label: "Systems",
          collapsed: true,
          items: [
            { type: 'doc', id: "distributed-systems", label: "Distributed Systems" },
            { type: 'doc', id: "graph-databases", label: "Graph Databases" },
            { type: 'doc', id: "high-performance-computing", label: "High-Performance Computing" },
            { type: 'doc', id: "networking", label: "Networking" },
            { type: 'doc', id: "operating-systems", label: "Operating Systems" },
            { type: 'doc', id: "parallel-computing", label: "Parallel Computing" },
            { type: 'doc', id: "relational-databases", label: "Relational Databases" },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
