/**
 * Local artifact ingestion (v2 runbook P01–P04).
 *
 * Fixtures are built here rather than committed, so the repository never
 * carries a binary blob, and **no fixture is ever executed**: a `.py` file is
 * decoded and stored as text, exactly as a researcher's own file would be.
 *
 * The notebook fixture deliberately contains a base64 image output and a
 * credential-shaped string in an output cell. Neither may appear in the
 * extracted text, because notebook outputs are where secrets leak in practice.
 */
import { describe, expect, it } from 'vitest';
import {
  ALLOWED_EXTENSIONS,
  EXTRACTION_TIMEOUT_MS,
  ExtractionError,
  MAX_EXTRACTED_CHARACTERS,
  MAX_PDF_PAGES,
  MAX_UPLOAD_BYTES,
  extensionOf,
  extractArtifact,
  isAllowedExtension,
  mediaTypeFor,
} from '../src/artifacts/index.js';
import {
  PersonalNotFoundError,
  PersonalValidationError,
  archiveArtifact,
  countArtifacts,
  createArtifact,
  createProject,
  getArtifactInProject,
  listArtifacts,
  openPersonalDatabase,
  restoreArtifact,
  selectArtifactsForContext,
} from '../src/personal/index.js';

const utf8 = (text: string): Uint8Array => new TextEncoder().encode(text);

/* -------------------------------------------------------------------------- */
/* A minimal, genuinely valid PDF, written by hand                             */
/* -------------------------------------------------------------------------- */

/**
 * Build a one-or-more page PDF whose pages carry the given lines of text.
 *
 * Written out by hand rather than generated by a library so the test depends on
 * nothing but the extractor under test, and so the bytes are obviously inert.
 */
function buildPdf(pages: readonly string[]): Uint8Array {
  const objects: string[] = [];
  const pageIds = pages.map((_, index) => 3 + index * 2);

  objects.push('<< /Type /Catalog /Pages 2 0 R >>');
  objects.push(
    `<< /Type /Pages /Kids [${pageIds.map((id) => `${String(id)} 0 R`).join(' ')}] /Count ${String(pages.length)} >>`,
  );

  pages.forEach((text, index) => {
    const pageId = pageIds[index]!;
    const contentId = pageId + 1;
    objects.push(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents ${String(contentId)} 0 R ` +
        `/Resources << /Font << /F1 ${String(3 + pages.length * 2)} 0 R >> >> >>`,
    );
    const escaped = text.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
    const stream = `BT /F1 12 Tf 72 720 Td (${escaped}) Tj ET`;
    objects.push(`<< /Length ${String(stream.length)} >>\nstream\n${stream}\nendstream`);
  });

  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');

  let body = '%PDF-1.4\n';
  const offsets: number[] = [];
  objects.forEach((object, index) => {
    offsets.push(body.length);
    body += `${String(index + 1)} 0 obj\n${object}\nendobj\n`;
  });

  const xrefAt = body.length;
  body += `xref\n0 ${String(objects.length + 1)}\n0000000000 65535 f \n`;
  for (const offset of offsets) {
    body += `${String(offset).padStart(10, '0')} 00000 n \n`;
  }
  body += `trailer\n<< /Size ${String(objects.length + 1)} /Root 1 0 R >>\nstartxref\n${String(xrefAt)}\n%%EOF\n`;
  return utf8(body);
}

/* -------------------------------------------------------------------------- */
/* P02 — text and code                                                         */
/* -------------------------------------------------------------------------- */

describe('text and code extraction', () => {
  it('accepts every allowed text extension', async () => {
    for (const extension of ALLOWED_EXTENSIONS) {
      if (extension === '.pdf' || extension === '.ipynb') continue;
      const result = await extractArtifact(`paper${extension}`, utf8('hello, research\n'));
      expect(result.text, extension).toBe('hello, research\n');
      expect(result.extension).toBe(extension);
      expect(result.characterCount).toBe(result.text.length);
      expect(result.sha256).toMatch(/^[0-9a-f]{64}$/);
    }
  });

  it('stores code as text and does not execute it', async () => {
    const source = [
      'import os',
      'os.system("touch /tmp/navigator-should-never-exist")',
      'print("hello")',
    ].join('\n');
    const result = await extractArtifact('run.py', utf8(source));
    expect(result.text).toContain('os.system');
    expect(result.mediaType).toBe('text/plain');
    const { existsSync } = await import('node:fs');
    expect(existsSync('/tmp/navigator-should-never-exist')).toBe(false);
  });

  it('normalises newlines and strips a byte-order mark', async () => {
    const result = await extractArtifact('notes.md', utf8('﻿one\r\ntwo\rthree\n'));
    expect(result.text).toBe('one\ntwo\nthree\n');
  });

  it('refuses an unsupported extension, naming what it does read', async () => {
    await expect(extractArtifact('slides.pptx', utf8('x'))).rejects.toThrow(ExtractionError);
    await expect(extractArtifact('slides.pptx', utf8('x'))).rejects.toThrow(/not read/);
    await expect(extractArtifact('noextension', utf8('x'))).rejects.toThrow(/no extension/);
  });

  it('refuses an empty file and one over the size limit', async () => {
    await expect(extractArtifact('empty.txt', new Uint8Array(0))).rejects.toThrow(/empty/);
    const huge = new Uint8Array(MAX_UPLOAD_BYTES + 1).fill(0x61);
    await expect(extractArtifact('huge.txt', huge)).rejects.toThrow(/the limit is/);
  });

  it('refuses binary content wearing a text extension', async () => {
    const png = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0, 0, 0, 13]);
    await expect(extractArtifact('image.txt', png)).rejects.toThrow(/binary data/);

    const mostlyControls = new Uint8Array(200).fill(0x01);
    await expect(extractArtifact('control.txt', mostlyControls)).rejects.toThrow(/binary data/);
  });

  it('warns rather than fails on invalid UTF-8', async () => {
    const bytes = new Uint8Array([...utf8('good '), 0xff, 0xfe, ...utf8(' text')]);
    const result = await extractArtifact('mixed.txt', bytes);
    expect(result.text).toContain('good');
    expect(result.warnings.join(' ')).toContain('not valid UTF-8');
  });

  it('caps extraction and says so', async () => {
    const long = 'a'.repeat(MAX_EXTRACTED_CHARACTERS + 5_000);
    const result = await extractArtifact('long.txt', utf8(long));
    expect(result.characterCount).toBe(MAX_EXTRACTED_CHARACTERS);
    expect(result.warnings.join(' ')).toContain('Extraction stopped at');
  });

  it('refuses a file that is only whitespace', async () => {
    await expect(extractArtifact('blank.txt', utf8('   \n\n  \n'))).rejects.toThrow(
      /No text could be extracted/,
    );
  });

  it('knows its own vocabulary', () => {
    expect(extensionOf('/a/b/paper.PDF')).toBe('.pdf');
    expect(extensionOf('noextension')).toBe('');
    expect(extensionOf('.hidden')).toBe('');
    expect(isAllowedExtension('.rs')).toBe(true);
    expect(isAllowedExtension('.exe')).toBe(false);
    expect(mediaTypeFor('.ipynb')).toBe('application/x-ipynb+json');
  });
});

/* -------------------------------------------------------------------------- */
/* P03 — notebooks                                                             */
/* -------------------------------------------------------------------------- */

const NOTEBOOK = JSON.stringify({
  cells: [
    { cell_type: 'markdown', source: ['# Recall experiment\n', '\n', 'Measuring at 512px.'] },
    { cell_type: 'code', source: 'import torch\nprint(model)\n', execution_count: 3 },
    {
      cell_type: 'code',
      source: 'display(figure)\n',
      outputs: [
        {
          output_type: 'display_data',
          data: {
            'image/png':
              'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
          },
        },
        { output_type: 'stream', text: 'SENTINEL-NOTEBOOK-OUTPUT-SECRET-91af\n' },
      ],
    },
    { cell_type: 'raw', source: 'raw cell contents' },
  ],
  metadata: { language_info: { name: 'python', version: '3.12' }, widgets: { state: {} } },
  nbformat: 4,
});

describe('notebook extraction', () => {
  it('keeps markdown and code source in cell order', async () => {
    const result = await extractArtifact('experiment.ipynb', utf8(NOTEBOOK));
    expect(result.text).toContain('# Recall experiment');
    expect(result.text).toContain('import torch');
    expect(result.text).toContain('cell 1 · markdown');
    expect(result.text).toContain('cell 2 · code');
    expect(result.text).toContain('language python');
    expect(result.mediaType).toBe('application/x-ipynb+json');
  });

  it('discards every output, including base64 images and a leaked secret', async () => {
    const result = await extractArtifact('experiment.ipynb', utf8(NOTEBOOK));
    expect(result.text).not.toContain('iVBORw0KGgo');
    expect(result.text).not.toContain('SENTINEL-NOTEBOOK-OUTPUT-SECRET-91af');
    expect(result.text).not.toContain('image/png');
    expect(result.text).not.toContain('execution_count');
    expect(result.text).not.toContain('widgets');
    expect(result.warnings.join(' ')).toContain('outputs, attachments and execution counts');
  });

  it('skips a cell that is neither markdown nor code, and says how many', async () => {
    const result = await extractArtifact('experiment.ipynb', utf8(NOTEBOOK));
    expect(result.warnings.join(' ')).toContain('1 cell(s) were neither markdown nor code');
    expect(result.text).not.toContain('raw cell contents');
  });

  it('refuses malformed JSON and a notebook with no cells', async () => {
    await expect(extractArtifact('broken.ipynb', utf8('{not json'))).rejects.toThrow(
      /not valid JSON/,
    );
    await expect(extractArtifact('empty.ipynb', utf8('{"metadata":{}}'))).rejects.toThrow(
      /no cell list/,
    );
    await expect(
      extractArtifact('silent.ipynb', utf8('{"cells":[{"cell_type":"code","source":""}]}')),
    ).rejects.toThrow(/no markdown or code text/);
  });
});

/* -------------------------------------------------------------------------- */
/* P04 — PDFs                                                                  */
/* -------------------------------------------------------------------------- */

describe('PDF extraction', () => {
  it('extracts text with explicit page markers', async () => {
    const pdf = buildPdf(['Residual connections ease optimisation.', 'Second page text.']);
    const result = await extractArtifact('paper.pdf', pdf);
    expect(result.text).toContain('[page 1]');
    expect(result.text).toContain('Residual connections ease optimisation.');
    expect(result.text).toContain('[page 2]');
    expect(result.text).toContain('Second page text.');
    expect(result.mediaType).toBe('application/pdf');
  }, 60_000);

  it('reports an image-only PDF as having no extractable text', async () => {
    // A valid PDF whose single page draws nothing.
    const blank = buildPdf(['']);
    await expect(extractArtifact('scan.pdf', blank)).rejects.toThrow(/scanned PDF/);
  }, 60_000);

  it('refuses a malformed PDF', async () => {
    await expect(extractArtifact('broken.pdf', utf8('%PDF-1.4\nnot really\n'))).rejects.toThrow(
      ExtractionError,
    );
  }, 60_000);

  it('stops at the page limit and says so', async () => {
    const many = buildPdf(
      Array.from({ length: MAX_PDF_PAGES + 3 }, (_, index) => `Page ${String(index + 1)} text.`),
    );
    const result = await extractArtifact('long.pdf', many);
    expect(result.warnings.join(' ')).toContain(`only the first ${String(MAX_PDF_PAGES)}`);
    expect(result.text).toContain(`[page ${String(MAX_PDF_PAGES)}]`);
    expect(result.text).not.toContain(`[page ${String(MAX_PDF_PAGES + 1)}]`);
  }, 120_000);

  it('stops when extraction takes too long', async () => {
    // The budget is checked by the page loop itself. A timer alone would never
    // fire: page extraction is CPU-bound and resolves through microtasks.
    const many = buildPdf(Array.from({ length: 60 }, (_, index) => `Page ${String(index)}.`));
    await expect(extractArtifact('slow.pdf', many, { timeoutMs: -1 })).rejects.toThrow(
      /taking too long/,
    );
    expect(EXTRACTION_TIMEOUT_MS).toBe(60_000);
  }, 60_000);
});

/* -------------------------------------------------------------------------- */
/* P01 — storage                                                               */
/* -------------------------------------------------------------------------- */

describe('artifact storage', () => {
  const sample = {
    label: 'ResNet paper',
    originalName: 'resnet.pdf',
    mediaType: 'application/pdf',
    byteCount: 1234,
    characterCount: 42,
    sha256: 'a'.repeat(64),
    warnings: ['One page could not be read.'],
    extractedText: '[page 1]\nResidual connections ease optimisation.',
  };

  it('creates, reads back text deliberately, and lists metadata only', () => {
    const db = openPersonalDatabase(':memory:');
    try {
      const project = createProject(db, { title: 'Papers' });
      const created = createArtifact(db, project.id, sample);
      expect(created.deduplicated).toBe(false);
      expect(created.artifact.label).toBe('ResNet paper');
      expect(created.artifact.warnings).toEqual(['One page could not be read.']);

      // A listing carries no extracted text at all.
      const listed = listArtifacts(db, project.id);
      expect(listed).toHaveLength(1);
      expect(Object.keys(listed[0]!)).not.toContain('extractedText');

      const full = getArtifactInProject(db, project.id, created.artifact.id);
      expect(full.extractedText).toContain('Residual connections');
    } finally {
      db.close();
    }
  });

  it('never stores the original bytes', () => {
    const db = openPersonalDatabase(':memory:');
    try {
      const columns = (db.prepare('PRAGMA table_info(artifacts)').all() as { name: string }[]).map(
        (column) => column.name,
      );
      expect(columns).toContain('extracted_text');
      expect(columns).toContain('sha256');
      for (const forbidden of ['bytes', 'blob', 'content', 'data', 'original']) {
        expect(columns.some((name) => name === forbidden)).toBe(false);
      }
      // `original_name` is the file's name, not its contents.
      expect(columns).toContain('original_name');
    } finally {
      db.close();
    }
  });

  it('deduplicates the same bytes inside one project, but not across projects', () => {
    const db = openPersonalDatabase(':memory:');
    try {
      const one = createProject(db, { title: 'One' });
      const two = createProject(db, { title: 'Two' });

      expect(createArtifact(db, one.id, sample).deduplicated).toBe(false);
      const again = createArtifact(db, one.id, { ...sample, label: 'Renamed' });
      expect(again.deduplicated).toBe(true);
      expect(again.artifact.label).toBe('ResNet paper');
      expect(countArtifacts(db, one.id)).toBe(1);

      expect(createArtifact(db, two.id, sample).deduplicated).toBe(false);
      expect(countArtifacts(db)).toBe(2);
    } finally {
      db.close();
    }
  });

  it('archives, restores, and un-archives on a repeat upload', () => {
    const db = openPersonalDatabase(':memory:');
    try {
      const project = createProject(db, { title: 'Lifecycle' });
      const artifact = createArtifact(db, project.id, sample).artifact;

      archiveArtifact(db, project.id, artifact.id);
      expect(listArtifacts(db, project.id)).toHaveLength(0);
      expect(listArtifacts(db, project.id, { includeArchived: true })).toHaveLength(1);

      restoreArtifact(db, project.id, artifact.id);
      expect(listArtifacts(db, project.id)).toHaveLength(1);

      archiveArtifact(db, project.id, artifact.id);
      const repeat = createArtifact(db, project.id, sample);
      expect(repeat.deduplicated).toBe(true);
      expect(repeat.artifact.archivedAt).toBeNull();
    } finally {
      db.close();
    }
  });

  it('refuses an artifact from another project, and an unknown project', () => {
    const db = openPersonalDatabase(':memory:');
    try {
      const one = createProject(db, { title: 'One' });
      const two = createProject(db, { title: 'Two' });
      const artifact = createArtifact(db, one.id, sample).artifact;

      expect(() => getArtifactInProject(db, two.id, artifact.id)).toThrow(PersonalNotFoundError);
      expect(() => archiveArtifact(db, two.id, artifact.id)).toThrow(PersonalNotFoundError);
      expect(() => createArtifact(db, 'nope', sample)).toThrow(PersonalNotFoundError);
    } finally {
      db.close();
    }
  });

  it('rejects malformed metadata', () => {
    const db = openPersonalDatabase(':memory:');
    try {
      const project = createProject(db, { title: 'Validation' });
      expect(() => createArtifact(db, project.id, { ...sample, sha256: 'nope' })).toThrow(
        PersonalValidationError,
      );
      expect(() => createArtifact(db, project.id, { ...sample, extractedText: '' })).toThrow(
        PersonalValidationError,
      );
      expect(() => createArtifact(db, project.id, { ...sample, extra: 1 })).toThrow(
        PersonalValidationError,
      );
    } finally {
      db.close();
    }
  });

  it('selects only the artifacts a caller named, from its own project', () => {
    const db = openPersonalDatabase(':memory:');
    try {
      const one = createProject(db, { title: 'One' });
      const two = createProject(db, { title: 'Two' });
      const mine = createArtifact(db, one.id, sample).artifact;
      const theirs = createArtifact(db, two.id, { ...sample, sha256: 'b'.repeat(64) }).artifact;
      const archived = createArtifact(db, one.id, {
        ...sample,
        sha256: 'c'.repeat(64),
        label: 'Archived',
      }).artifact;
      archiveArtifact(db, one.id, archived.id);

      const selected = selectArtifactsForContext(db, one.id, [
        mine.id,
        theirs.id,
        archived.id,
        'not-an-id',
      ]);
      expect(selected.map((artifact) => artifact.id)).toEqual([mine.id]);
    } finally {
      db.close();
    }
  });
});
